### ISSUE TITLE
incr is not a function

### ISSUE THREAD

**Issue by weihao** [wyattjoh/rate-limit-redis#27]
```
Unhandled Error TypeError: options.client.multi(...).incr is not a function
    at RedisStore.incr (/Users/user/Documents/GitHub/demo/node_modules/rate-limit-redis/lib/redis-store.js:46:8)
    at rateLimit (/Users/user/Documents/GitHub/demo/node_modules/express-rate-limit/lib/express-rate-limit.js:59:19)
    at Layer.handle [as handle_request] (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:317:13)
    at /Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:317:13)
    at /Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:275:10)
    at /Users/user/Documents/GitHub/demo/node_modules/request-ip/dist/index.js:164:5
    at Layer.handle [as handle_request] (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:317:13)
    at /Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:284:7
(node:23587) UnhandledPromiseRejectionWarning: TypeError: executor is not a function
    at /Users/user/Documents/GitHub/demo/server/redis.ts:77:9
    at new Promise (<anonymous>)
    at demoRedis.multi (/Users/user/Documents/GitHub/demo/server/redis.ts:74:12)
    at RedisStore.incr (/Users/user/Documents/GitHub/demo/node_modules/rate-limit-redis/lib/redis-store.js:45:20)
    at rateLimit (/Users/user/Documents/GitHub/demo/node_modules/express-rate-limit/lib/express-rate-limit.js:59:19)
    at Layer.handle [as handle_request] (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:317:13)
    at /Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:317:13)
    at /Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/user/Documents/GitHub/demo/node_modules/express/lib/router/index.js:275:10)
    at /Users/user/Documents/GitHub/demo/node_modules/request-ip/dist/index.js:164:5
```

**Comment by weihao** [comment]
solved, use:

```
  app.use(new RateLimit({
    store: new RedisStore({
      client: redis.client // you need to use client
    }),
    max: 100,
    delayMs: 0
  }))
```

**Comment by weihao** [comment]
related to #24
