### ISSUE TITLE
 Unable to work with redis when cluster mode is enabled

### ISSUE THREAD

**Issue by krishna-unibuddy** [wyattjoh/rate-limit-redis#55]
### Description

We are using redis in cluster mode. When I test it with redis with cluster mode enabled, `sendCommand` functions hangs and never returns any response.

```
import rateLimit from "express-rate-limit";
import { createCluster } from "redis";
import RedisStore from "rate-limit-redis";

const createRateLimiter = async(({}) => {
  const cluster = createCluster({
    rootNodes: [
      {
        url: "redis://127.0.0.1:6379",
      },
    ],
  });
  await cluster.connect();

  return rateLimit({
    store: new RedisStore({
      sendCommand: (...args) => cluster.sendCommand(args),
    }),
  });
});
```

### Library version

3.0.0

### Node version

v14.16.1

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @krishna-unibuddy,

Thanks for opening this issue and sorry for the late reply.

Here is what I did to try reproducing the issue:

- Run a redis cluster (3 parent, 3 child, on ports 7000-7005) using docker as follows:
```sh
> docker run --name rate-limit-redis -i -t -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 -d grokzen/redis-cluster
```
- Run the following code:
```ts
// /source/index.ts
// Run a basic express server that uses the node-redis client for rate limiting
// Run using `ts-node source/index.ts`

import { createCluster } from 'redis'
import createServer from 'express'
import rateLimit from 'express-rate-limit'
import RedisStore from 'rate-limit-redis'

const main = async () => {
	const app = createServer()

	const cluster = createCluster({
		rootNodes: [
			{
				url: 'redis://127.0.0.1:7000',
			},
			{
				url: 'redis://127.0.0.1:7001',
			},
			{
				url: 'redis://127.0.0.1:7002',
			},
			{
				url: 'redis://127.0.0.1:7003',
			},
			{
				url: 'redis://127.0.0.1:7004',
			},
			{
				url: 'redis://127.0.0.1:7005',
			},
		],
	})
	await cluster.connect()

	const limiter = rateLimit({
		max: 3,
		windowMs: 10_000,
		store: new RedisStore({
			sendCommand: async (...args: string[]) =>
				cluster.sendCommand(args[0], false, args),
		}),
		skip: (request) => request.url === '/reset',
	})

	app.use('/', limiter)

	app.get('/ip', (request, response) => response.send({ ip: request.ip }))
	app.get('/quota', (request, response) =>
		// @ts-expect-error
		response.send({ quota: request.rateLimit }),
	)
	app.get('/reset', (request, response) => {
		limiter.resetKey(request.ip)
		response.send({ ip: request.ip, reset: true })
	})

	app.listen(8080, () => {
		console.log('Server running!')
		console.log('http://localhost:8080/ip => view your IP address')
		console.log('http://localhost:8080/quota => view your rate limit')
		console.log('http://localhost:8080/reset => reset your rate limit')
	})
}

main()
```
- Notice that the `sendCommand` function is changed to match the call signature of the `cluster#sendCommand` function - `#sendCommand(<command>, <isReadOnly>, <args>)`
- This gave me a `NOSCRIPT: Please use EVAL` error every time I made a request to the server. This is because the lua script used to increment the hit count for a user is loaded only on one redis node when we make the `SCRIPT LOAD` call. So if we try to run the script on a different node, the script won't run as it doesn't exist on the other node. [Here](https://nickolasfisher.com/blog/Pre-Loading-Lua-Scripts-into-Clustered-Redis-with-Lettuce) is an article that I found that explains the same.
- To fix this, I tried replacing usage of `EVALSHA` with `EVAL` in the code - so instead of loading the script once, we would pass the script everytime to the server. Here is the diff of the change (save this file as `with-eval-change-code.patch` and run `patch node_modules/rate-limit-redis/dist/index.cjs with-eval-change-code.patch`):
```diff
diff --git a/existing-code.cjs b/node_modules/rate-limit-redis/dist/index.cjs
index 91ff1b9..d53f3cc 100644
--- a/existing-code.cjs
+++ b/node_modules/rate-limit-redis/dist/index.cjs
@@ -32,30 +32,23 @@ var RedisStore = class {
   sendCommand;
   prefix;
   resetExpiryOnChange;
-  loadedScriptSha1;
+  script;
   windowMs;
   constructor(options) {
     this.sendCommand = options.sendCommand;
     this.prefix = options.prefix ?? "rl:";
     this.resetExpiryOnChange = options.resetExpiryOnChange ?? false;
-    this.loadedScriptSha1 = this.loadScript();
-  }
-  async loadScript() {
-    const result = await this.sendCommand("SCRIPT", "LOAD", `
-        local totalHits = redis.call("INCR", KEYS[1])
-        local timeToExpire = redis.call("PTTL", KEYS[1])
-        if timeToExpire <= 0 or ARGV[1] == "1"
-        then
-            redis.call("PEXPIRE", KEYS[1], tonumber(ARGV[2]))
-            timeToExpire = tonumber(ARGV[2])
-        end
-
-        return { totalHits, timeToExpire }
-    `.replace(/^\s+/gm, "").trim());
-    if (typeof result !== "string") {
-      throw new TypeError("unexpected reply from redis client");
-    }
-    return result;
+    this.script = `
+            local totalHits = redis.call("INCR", KEYS[1])
+            local timeToExpire = redis.call("PTTL", KEYS[1])
+            if timeToExpire <= 0 or ARGV[1] == "1"
+            then
+                redis.call("PEXPIRE", KEYS[1], tonumber(ARGV[2]))
+                timeToExpire = tonumber(ARGV[2])
+            end
+    
+            return { totalHits, timeToExpire }
+        `.replace(/^\s+/gm, "").trim()
   }
   prefixKey(key) {
     return `${this.prefix}${key}`;
@@ -64,7 +57,7 @@ var RedisStore = class {
     this.windowMs = options.windowMs;
   }
   async increment(key) {
-    const results = await this.sendCommand("EVALSHA", await this.loadedScriptSha1, "1", this.prefixKey(key), this.resetExpiryOnChange ? "1" : "0", this.windowMs.toString());
+    const results = await this.sendCommand("EVAL", this.script, "1", this.prefixKey(key), this.resetExpiryOnChange ? "1" : "0", this.windowMs.toString());
     if (!Array.isArray(results)) {
       throw new TypeError("Expected result to be array of values");
     }
```
- Even with this patch, I get the following error:
```sh
ReplyError: MOVED 5665 172.17.0.2:7001
    at parseError (redis-test-app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (redis-test-app/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
```
- I thought `node-redis` would handle a `MOVED` error and retry the call to the correct node but this does not seem to be the case. I'm not sure how we would handle this manually without making an HTTP call to the given IP (and even that will result in an error - the IP given in the error is the IP address of the node inside the docker container, the actual IP is 127.0.0.1:7001).
- Also, I'm not sure which nodes are parent and which nodes are child - maybe I made a mistake in putting all six in the `rootNodes` array?

As a temporary workaround, maybe you could create another non-cluster redis client with `url` set to only one parent node and use that _only with the rate limiter_?

**Comment by krishna-unibuddy** [comment]
Hi ,
We created custom `RedisStore` for the moment. This issue is still relevant. Sorry, I did not get more time to invest on this since I last worked on it.

**Comment by gamemaker1** [comment]
If you have the time, could you share the store you wrote? It might help adding support for clusters to this library. Thanks :)
